name: jday
description: 간단한 일정 관리 앱

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.7
  intl: ^0.18.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_riverpod: ^2.0.2

  cloud_firestore: ^4.13.6
  firebase_helpers: ^0.6.1

  # for OCR
  http: ^1.1.2
  path_provider: ^2.0.11
  image: ^4.1.3
  image_picker: ^1.0.5
  image_picker_for_web: ^3.0.1
  mime: ^1.0.2  # file format

  # for weather
  geolocator: ^10.1.0

  cupertino_icons: ^1.0.2

  flutter_dotenv: ^5.1.0
  web: '>=0.3.0 <0.5.0'
  cloud_functions: ^4.5.8
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/img-res/
    - .env
    
  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.otf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.otf
          weight: 200
        - asset: assets/font/SUIT-Light.otf
          weight: 300
        - asset: assets/font/SUIT-Regular.otf
          weight: 400
        - asset: assets/font/SUIT-Medium.otf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.otf
          weight: 600
        - asset: assets/font/SUIT-Bold.otf
          weight: 700
        - asset: assets/font/SUIT-ExtraBold.otf
          weight: 800
        - asset: assets/font/SUIT-Heavy.otf
          weight: 900