// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6G7Ac4-wHwCjLJR3EoPrS71zFX_bHGxU',
    appId: '1:978595336231:web:107781afef6ec12a47be02',
    messagingSenderId: '978595336231',
    projectId: 'jday-4df6b',
    authDomain: 'jday-4df6b.firebaseapp.com',
    storageBucket: 'jday-4df6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXgTbcBluiR5HAyIsqO1zVSWPmL0rbgU',
    appId: '1:978595336231:android:ce501445c8e5358347be02',
    messagingSenderId: '978595336231',
    projectId: 'jday-4df6b',
    storageBucket: 'jday-4df6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfo-nQv_yhpH6WNTmHAsUvVmTpmGCRfNg',
    appId: '1:978595336231:ios:28fb3c9e76a8a99647be02',
    messagingSenderId: '978595336231',
    projectId: 'jday-4df6b',
    storageBucket: 'jday-4df6b.appspot.com',
    iosClientId: '978595336231-vhjd73dc4ni48v3250jfdduikq4af7ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.jday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfo-nQv_yhpH6WNTmHAsUvVmTpmGCRfNg',
    appId: '1:978595336231:ios:28fb3c9e76a8a99647be02',
    messagingSenderId: '978595336231',
    projectId: 'jday-4df6b',
    storageBucket: 'jday-4df6b.appspot.com',
    iosClientId: '978595336231-vhjd73dc4ni48v3250jfdduikq4af7ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.jday',
  );
}
